
import type { ServiceProvider, ServiceCategory, Review } from '@/types';

export const serviceCategories: { value: ServiceCategory; label: string }[] = [
  { value: "Painting", label: "Painting" },
  { value: "Gardening", label: "Gardening" },
  { value: "Plumbing", label: "Plumbing" },
  { value: "Cleaning", label: "Cleaning" },
  { value: "Electrical", label: "Electrical" },
  { value: "Handyman", label: "General Handyman" },
  { value: "Landscaping", label: "Landscaping" },
  { value: "Other", label: "Other" },
];

const generateReviews = (providerName: string, baseRating: number): Review[] => {
  const reviews: Review[] = [];
  const reviewCount = Math.floor(Math.random() * 8) + 3; // 3 to 10 reviews
  const names = ["Aarav S.", "Isha K.", "Vihaan M.", "Myra D.", "Advik P.", "Anaya R.", "Rohan J.", "Saanvi T."];
  const comments = [
    `Excellent work by ${providerName}! Very professional and punctual.`,
    `${providerName} did a fantastic job. Highly recommended!`,
    `Very satisfied with ${providerName}'s service. Will hire again.`,
    `Good communication and quality work from ${providerName}.`,
    `A reliable professional. ${providerName} understood my requirements well.`,
    `The project was completed on time and within budget by ${providerName}.`,
    `Impressed with the attention to detail shown by ${providerName}.`,
  ];

  for (let i = 0; i < reviewCount; i++) {
    reviews.push({
      id: `${providerName.replace(/\s+/g, '-')}-review-${i + Date.now()}`,
      reviewerName: names[Math.floor(Math.random() * names.length)],
      rating: Math.min(5, Math.max(3, baseRating - 1 + Math.random() * 2)), // Rating around baseRating, min 3
      comment: comments[Math.floor(Math.random() * comments.length)],
      date: new Date(Date.now() - Math.floor(Math.random() * 90) * 24 * 60 * 60 * 1000).toISOString(),
    });
  }
  return reviews;
};


export const dummyProviders: ServiceProvider[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    serviceTypes: ['Painting', 'Handyman'],
    rating: 4.8,
    location: 'Mandya, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Priya+S',
    bio: 'Experienced painter and general handyman with over 10 years in Mandya. Detail-oriented and committed to quality work. I specialize in residential and commercial painting, offering a range of finishes and techniques. Also proficient in minor plumbing, electrical fixes, and furniture assembly.',
    experienceYears: 10,
    hourlyRate: '350-500',
    reviewsCount: 120,
    portfolioImages: [
      'https://placehold.co/600x400.png?text=Painting+Project+1',
      'https://placehold.co/600x400.png?text=Handyman+Repair',
      'https://placehold.co/600x400.png?text=Interior+Work'
    ],
    reviews: generateReviews('Priya Sharma', 4.8),
  },
  {
    id: '2',
    name: 'Rohan Gowda',
    serviceTypes: ['Gardening', 'Landscaping'],
    rating: 4.5,
    location: 'Mandya, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Rohan+G',
    bio: 'Passionate gardener and landscaper transforming outdoor spaces in Mandya and nearby areas. Specializes in sustainable gardening practices, landscape design, and regular garden maintenance. From lawn care to creating beautiful flower beds, I can help your garden thrive.',
    experienceYears: 7,
    hourlyRate: '300-450',
    reviewsCount: 85,
    portfolioImages: [
      'https://placehold.co/600x400.png?text=Garden+Makeover',
      'https://placehold.co/600x400.png?text=Lawn+Care',
    ],
    reviews: generateReviews('Rohan Gowda', 4.5),
  },
  {
    id: '3',
    name: 'Ananya Reddy',
    serviceTypes: ['Plumbing'],
    rating: 4.9,
    location: 'Mysuru, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Ananya+R',
    bio: 'Licensed plumber based in Mysuru, providing reliable and efficient solutions. Emergency services available 24/7. Expertise in leak detection, pipe repairs, fixture installations, and drain cleaning.',
    experienceYears: 12,
    hourlyRate: '400-600',
    reviewsCount: 200,
    reviews: generateReviews('Ananya Reddy', 4.9),
  },
  {
    id: '4',
    name: 'Vikram Singh',
    serviceTypes: ['Cleaning', 'Handyman'],
    rating: 4.3,
    location: 'Hassan, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Vikram+S',
    bio: 'Dedicated to making your home spotless and functional in Hassan. Offering regular house cleaning, deep cleaning services, and minor repair tasks. I bring my own eco-friendly cleaning supplies.',
    experienceYears: 5,
    hourlyRate: '250-400',
    reviewsCount: 65,
     portfolioImages: [
      'https://placehold.co/600x400.png?text=Sparkling+Clean+Kitchen',
      'https://placehold.co/600x400.png?text=Odd+Job+Fixed',
    ],
    reviews: generateReviews('Vikram Singh', 4.3),
  },
   {
    id: '5',
    name: 'Susmita Banerjee',
    serviceTypes: ['Electrical'],
    rating: 4.7,
    location: 'Mandya, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Susmita+B',
    bio: 'Certified electrician in Mandya ensuring safety and quality for all electrical installations and repairs. Experienced in wiring, light fixture installation, circuit breaker issues, and smart home setups.',
    experienceYears: 8,
    hourlyRate: '380-550',
    reviewsCount: 92,
    reviews: generateReviews('Susmita Banerjee', 4.7),
  },
  {
    id: '6',
    name: 'Arjun Rao',
    serviceTypes: ['Handyman', 'Painting', 'Plumbing'],
    rating: 4.6,
    location: 'Mandya, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Arjun+R',
    bio: 'Versatile handyman skilled in various trades serving Mandya district. Your go-to for home maintenance and improvements. Proficient in painting, minor plumbing repairs, carpentry, and general upkeep tasks.',
    experienceYears: 15,
    hourlyRate: '320-480',
    reviewsCount: 150,
    reviews: generateReviews('Arjun Rao', 4.6),
  },
  {
    id: '7',
    name: 'Kavya Murthy',
    serviceTypes: ['Cleaning'],
    rating: 4.9,
    location: 'Bengaluru, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Kavya+M',
    bio: 'Top-rated cleaning professional in Bengaluru. Eco-friendly products, thorough deep cleaning, and regular maintenance plans available. Your satisfaction is my priority.',
    experienceYears: 6,
    hourlyRate: '300-500',
    reviewsCount: 110,
    reviews: generateReviews('Kavya Murthy', 4.9),
  },
  {
    id: '8',
    name: 'Manjunath Patil',
    serviceTypes: ['Electrical', 'Handyman'],
    rating: 4.4,
    location: 'Hubballi-Dharwad, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Manjunath+P',
    bio: 'Reliable electrician and handyman service for Hubballi-Dharwad. From fixing faulty wiring to assembling furniture, I handle a variety of tasks efficiently.',
    experienceYears: 9,
    hourlyRate: '280-420',
    reviewsCount: 75,
    reviews: generateReviews('Manjunath Patil', 4.4),
  },
  {
    id: '9',
    name: 'Lakshmi Narayan',
    serviceTypes: ['Gardening'],
    rating: 4.7,
    location: 'Mandya, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Lakshmi+N',
    bio: 'Expert gardener in Mandya with a green thumb. Specializing in organic vegetable gardening, flower bed design, and tree pruning. Let me bring your garden to life!',
    experienceYears: 12,
    hourlyRate: '350-550',
    reviewsCount: 95,
    reviews: generateReviews('Lakshmi Narayan', 4.7),
  },
  {
    id: '10',
    name: 'Siddharth Chavan',
    serviceTypes: ['Plumbing', 'Handyman'],
    rating: 4.2,
    location: 'Shivamogga, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Siddharth+C',
    bio: 'Your friendly neighborhood plumber and handyman in Shivamogga. Quick response for leaks, installations, and general repairs. Affordable and trustworthy.',
    experienceYears: 4,
    hourlyRate: '220-380',
    reviewsCount: 50,
    reviews: generateReviews('Siddharth Chavan', 4.2),
  },
  {
    id: '11',
    name: 'Divya Hegde',
    serviceTypes: ['Painting'],
    rating: 4.8,
    location: 'Udupi, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Divya+H',
    bio: 'Professional painter in Udupi known for meticulous work and creative solutions. Interior, exterior, and decorative painting services. Using high-quality, durable paints.',
    experienceYears: 7,
    hourlyRate: '400-600',
    reviewsCount: 130,
    reviews: generateReviews('Divya Hegde', 4.8),
  },
  {
    id: '12',
    name: 'Ganesh Bhat',
    serviceTypes: ['Landscaping', 'Handyman'],
    rating: 4.6,
    location: 'Mandya, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Ganesh+B',
    bio: 'Complete landscaping and handyman services in Mandya. From designing beautiful gardens to handling various home repairs, I offer comprehensive solutions with a smile.',
    experienceYears: 11,
    hourlyRate: '330-520',
    reviewsCount: 105,
    reviews: generateReviews('Ganesh Bhat', 4.6),
  },
   {
    id: '13',
    name: 'Meena Kumari',
    serviceTypes: ['Cleaning', 'Other'],
    rating: 4.5,
    location: 'Tumakuru, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Meena+K',
    bio: 'Specialized cleaning services and home organization expert in Tumakuru. Offering decluttering, move-in/move-out cleaning, and customized cleaning plans.',
    experienceYears: 5,
    hourlyRate: '280-450',
    reviewsCount: 70,
    reviews: generateReviews('Meena Kumari', 4.5),
  },
  {
    id: '14',
    name: 'Santosh Kumar',
    serviceTypes: ['Electrical'],
    rating: 4.7,
    location: 'Mandya, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Santosh+K',
    bio: 'Quick and reliable electrical services in Mandya. Available for emergency repairs, new installations, and safety inspections. Your safety is my top concern.',
    experienceYears: 9,
    hourlyRate: '350-500',
    reviewsCount: 88,
    reviews: generateReviews('Santosh Kumar', 4.7),
  },
  {
    id: '15',
    name: 'Bharathi Ranganath',
    serviceTypes: ['Handyman', 'Plumbing'],
    rating: 4.4,
    location: 'Chikkamagaluru, Karnataka',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Bharathi+R',
    bio: 'All-round handyman and plumber serving Chikkamagaluru. No job too small, from leaky faucets to assembling flat-pack furniture. Dependable and fair pricing.',
    experienceYears: 6,
    hourlyRate: '250-420',
    reviewsCount: 60,
    reviews: generateReviews('Bharathi Ranganath', 4.4),
  },
  // --- NEW PROVIDERS START HERE ---
  {
    id: '16',
    name: 'Rajesh Patel',
    serviceTypes: ['Electrical', 'Handyman'],
    rating: 4.7,
    location: 'Ahmedabad, Gujarat',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Rajesh+P',
    bio: 'Certified electrician with 15 years of experience in Ahmedabad. I handle all types of electrical work, from new wiring to troubleshooting complex issues. Also offer general handyman services.',
    experienceYears: 15,
    hourlyRate: '400-550',
    reviewsCount: 135,
    portfolioImages: [
      'https://placehold.co/600x400.png?text=Electrical+Panel',
      'https://placehold.co/600x400.png?text=Fixture+Installation',
    ],
    reviews: generateReviews('Rajesh Patel', 4.7),
  },
  {
    id: '17',
    name: 'Sunita Sharma',
    serviceTypes: ['Cleaning', 'Other'],
    rating: 4.9,
    location: 'Delhi, NCR',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Sunita+S',
    bio: 'Professional cleaning services for homes and offices in Delhi. I use eco-friendly products and ensure a sparkling clean environment. Specialized in deep cleaning and post-event cleanup.',
    experienceYears: 8,
    hourlyRate: '350-500',
    reviewsCount: 180,
    reviews: generateReviews('Sunita Sharma', 4.9),
  },
  {
    id: '18',
    name: 'Amit Kumar Verma',
    serviceTypes: ['Plumbing'],
    rating: 4.6,
    location: 'Lucknow, Uttar Pradesh',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Amit+KV',
    bio: 'Your reliable plumber in Lucknow. Offering quick and efficient solutions for all plumbing problems, including leaks, blockages, and installations. Customer satisfaction guaranteed.',
    experienceYears: 10,
    hourlyRate: '300-480',
    reviewsCount: 95,
    portfolioImages: [
      'https://placehold.co/600x400.png?text=Pipe+Repair',
    ],
    reviews: generateReviews('Amit Kumar Verma', 4.6),
  },
  {
    id: '19',
    name: 'Deepika Nair',
    serviceTypes: ['Painting', 'Gardening'],
    rating: 4.5,
    location: 'Kochi, Kerala',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Deepika+N',
    bio: 'Creative painter and passionate gardener in Kochi. I bring color to your homes and life to your gardens. Experienced in mural painting, interior/exterior painting, and garden design.',
    experienceYears: 7,
    hourlyRate: '380-600',
    reviewsCount: 77,
    reviews: generateReviews('Deepika Nair', 4.5),
  },
  {
    id: '20',
    name: 'Karthik Reddy',
    serviceTypes: ['Handyman', 'Electrical'],
    rating: 4.4,
    location: 'Hyderabad, Telangana',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Karthik+R',
    bio: 'Skilled handyman and electrician serving Hyderabad. I provide quick fixes for common household problems, furniture assembly, and electrical repairs. Known for prompt service.',
    experienceYears: 6,
    hourlyRate: '280-450',
    reviewsCount: 60,
    reviews: generateReviews('Karthik Reddy', 4.4),
  },
  {
    id: '21',
    name: 'Neha Joshi',
    serviceTypes: ['Landscaping', 'Gardening'],
    rating: 4.8,
    location: 'Pune, Maharashtra',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Neha+J',
    bio: 'Professional landscaper and garden designer in Pune. I create beautiful and sustainable outdoor spaces, from small balconies to large yards. Offering consultation and execution.',
    experienceYears: 9,
    hourlyRate: '450-700',
    reviewsCount: 115,
    portfolioImages: [
        'https://placehold.co/600x400.png?text=Landscape+Design',
        'https://placehold.co/600x400.png?text=Garden+Installation'
    ],
    reviews: generateReviews('Neha Joshi', 4.8),
  },
  {
    id: '22',
    name: 'Sameer Khan',
    serviceTypes: ['Painting'],
    rating: 4.7,
    location: 'Mumbai, Maharashtra',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Sameer+K',
    bio: 'Expert painter in Mumbai with a keen eye for detail. Specialized in luxury finishes, textured painting, and quick makeovers for residential and commercial properties.',
    experienceYears: 12,
    hourlyRate: '500-750',
    reviewsCount: 150,
    reviews: generateReviews('Sameer Khan', 4.7),
  },
  {
    id: '23',
    name: 'Pooja Singh',
    serviceTypes: ['Cleaning'],
    rating: 4.6,
    location: 'Jaipur, Rajasthan',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Pooja+S',
    bio: 'Thorough and reliable cleaning services in Jaipur. I offer regular cleaning schedules, one-time deep cleans, and specialized services for homes and businesses.',
    experienceYears: 5,
    hourlyRate: '250-400',
    reviewsCount: 82,
    reviews: generateReviews('Pooja Singh', 4.6),
  },
  {
    id: '24',
    name: 'Arun Das',
    serviceTypes: ['Plumbing', 'Handyman'],
    rating: 4.3,
    location: 'Kolkata, West Bengal',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Arun+D',
    bio: 'Experienced plumber and handyman in Kolkata. Available for all kinds of plumbing repairs, installations, and general home maintenance tasks. Fair pricing and reliable service.',
    experienceYears: 18,
    hourlyRate: '300-450',
    reviewsCount: 102,
    reviews: generateReviews('Arun Das', 4.3),
  },
  {
    id: '25',
    name: 'Gayatri Patil',
    serviceTypes: ['Gardening', 'Other'],
    rating: 4.9,
    location: 'Goa',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Gayatri+P',
    bio: 'Specialized in tropical gardening and organic farming consultancy in Goa. I help create lush, productive gardens and also offer plant care services. Other services include composting workshops.',
    experienceYears: 10,
    hourlyRate: '400-650',
    reviewsCount: 90,
    reviews: generateReviews('Gayatri Patil', 4.9),
  },
  {
    id: '26',
    name: 'Mahesh Babu',
    serviceTypes: ['Electrical'],
    rating: 4.5,
    location: 'Chennai, Tamil Nadu',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Mahesh+B',
    bio: 'Licensed electrician in Chennai, providing safe and efficient electrical solutions. Expertise in residential wiring, appliance installation, and power backup systems.',
    experienceYears: 7,
    hourlyRate: '350-550',
    reviewsCount: 70,
    reviews: generateReviews('Mahesh Babu', 4.5),
  },
  {
    id: '27',
    name: 'Suresh Reddy',
    serviceTypes: ['Handyman', 'Painting'],
    rating: 4.6,
    location: 'Vijayawada, Andhra Pradesh',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Suresh+R',
    bio: 'Reliable handyman and painter serving Vijayawada. For all your small to medium home repair and painting needs, count on me for quality work and timely completion.',
    experienceYears: 9,
    hourlyRate: '280-480',
    reviewsCount: 88,
    reviews: generateReviews('Suresh Reddy', 4.6),
  },
  {
    id: '28',
    name: 'Anjali Menon',
    serviceTypes: ['Cleaning', 'Landscaping'],
    rating: 4.7,
    location: 'Coimbatore, Tamil Nadu',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Anjali+M',
    bio: 'Comprehensive cleaning and landscaping services in Coimbatore. I manage everything from keeping your interiors pristine to designing and maintaining beautiful outdoor areas.',
    experienceYears: 6,
    hourlyRate: '320-520',
    reviewsCount: 93,
    reviews: generateReviews('Anjali Menon', 4.7),
  },
  {
    id: '29',
    name: 'Rahul Tiwari',
    serviceTypes: ['Plumbing'],
    rating: 4.2,
    location: 'Bhopal, Madhya Pradesh',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Rahul+T',
    bio: 'Plumbing services in Bhopal. Specializing in quick fixes for leaks, tap replacements, and drain cleaning. Available for urgent requests.',
    experienceYears: 5,
    hourlyRate: '250-400',
    reviewsCount: 45,
    reviews: generateReviews('Rahul Tiwari', 4.2),
  },
  {
    id: '30',
    name: 'Priyanka Mehra',
    serviceTypes: ['Painting', 'Other'],
    rating: 4.8,
    location: 'Chandigarh',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Priyanka+M',
    bio: 'Professional interior and exterior painter in Chandigarh. Also offer custom wall art and decor painting services. Committed to transforming spaces with color.',
    experienceYears: 8,
    hourlyRate: '450-700',
    reviewsCount: 110,
    portfolioImages: [
      'https://placehold.co/600x400.png?text=Wall+Art+Project',
      'https://placehold.co/600x400.png?text=Exterior+Painting',
    ],
    reviews: generateReviews('Priyanka Mehra', 4.8),
  },
  {
    id: '31',
    name: 'Deepak Sharma',
    serviceTypes: ['Gardening', 'Handyman'],
    rating: 4.6,
    location: 'Indore, Madhya Pradesh',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Deepak+S',
    bio: 'Gardening expert and general handyman based in Indore. I help with garden setup, maintenance, and also undertake various small repair jobs around the house.',
    experienceYears: 11,
    hourlyRate: '300-480',
    reviewsCount: 98,
    reviews: generateReviews('Deepak Sharma', 4.6),
  },
  {
    id: '32',
    name: 'Nisha Gupta',
    serviceTypes: ['Electrical', 'Cleaning'],
    rating: 4.4,
    location: 'Nagpur, Maharashtra',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Nisha+G',
    bio: 'Qualified electrician and meticulous cleaner in Nagpur. I ensure your electrical systems are safe and your spaces are tidy. Offering combined service packages.',
    experienceYears: 7,
    hourlyRate: '320-500',
    reviewsCount: 72,
    reviews: generateReviews('Nisha Gupta', 4.4),
  },
  {
    id: '33',
    name: 'Alok Verma',
    serviceTypes: ['Plumbing'],
    rating: 4.7,
    location: 'Patna, Bihar',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Alok+V',
    bio: 'Reliable and affordable plumbing services in Patna. I handle installations, repairs, and maintenance for residential and commercial clients. 24/7 emergency service available.',
    experienceYears: 14,
    hourlyRate: '280-420',
    reviewsCount: 125,
    reviews: generateReviews('Alok Verma', 4.7),
  },
  {
    id: '34',
    name: 'Shanti Devi',
    serviceTypes: ['Cleaning', 'Other'],
    rating: 4.9,
    location: 'Ranchi, Jharkhand',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Shanti+D',
    bio: 'Dedicated cleaning professional in Ranchi. Also offer cooking and elderly care support as part of "Other" services. Trustworthy and compassionate.',
    experienceYears: 9,
    hourlyRate: '250-450',
    reviewsCount: 160,
    reviews: generateReviews('Shanti Devi', 4.9),
  },
  {
    id: '35',
    name: 'Ravi Shankar',
    serviceTypes: ['Painting', 'Handyman'],
    rating: 4.5,
    location: 'Bhubaneswar, Odisha',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Ravi+S',
    bio: 'Skilled painter and handyman in Bhubaneswar. Offering quality painting services and a wide range of home repair solutions. Committed to customer satisfaction.',
    experienceYears: 10,
    hourlyRate: '350-550',
    reviewsCount: 80,
    reviews: generateReviews('Ravi Shankar', 4.5),
  },
  {
    id: '36',
    name: 'Ishaan Patel',
    serviceTypes: ['Landscaping', 'Electrical'],
    rating: 4.6,
    location: 'Surat, Gujarat',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Ishaan+P',
    bio: 'Creative landscaper and certified electrician in Surat. I design beautiful outdoor spaces and also handle all electrical wiring and installation needs.',
    experienceYears: 8,
    hourlyRate: '400-600',
    reviewsCount: 99,
    reviews: generateReviews('Ishaan Patel', 4.6),
  },
  {
    id: '37',
    name: 'Aisha Begum',
    serviceTypes: ['Gardening'],
    rating: 4.8,
    location: 'Guwahati, Assam',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Aisha+B',
    bio: 'Passionate gardener in Guwahati specializing in rooftop gardens and organic vegetable cultivation. Let me help you create a green oasis in your urban space.',
    experienceYears: 6,
    hourlyRate: '300-500',
    reviewsCount: 75,
    reviews: generateReviews('Aisha Begum', 4.8),
  },
  {
    id: '38',
    name: 'Vivek Anand',
    serviceTypes: ['Handyman', 'Plumbing', 'Electrical'],
    rating: 4.3,
    location: 'Dehradun, Uttarakhand',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Vivek+A',
    bio: 'All-in-one handyman services in Dehradun. Proficient in plumbing, electrical, and minor carpentry work. Your one-stop solution for home maintenance.',
    experienceYears: 12,
    hourlyRate: '320-500',
    reviewsCount: 110,
    reviews: generateReviews('Vivek Anand', 4.3),
  },
  {
    id: '39',
    name: 'Meera Chauhan',
    serviceTypes: ['Painting', 'Cleaning'],
    rating: 4.7,
    location: 'Shimla, Himachal Pradesh',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Meera+C',
    bio: 'Professional painting and cleaning services for homes and guesthouses in Shimla. I use quality materials and ensure a perfect finish. Attention to detail is my specialty.',
    experienceYears: 9,
    hourlyRate: '380-600',
    reviewsCount: 105,
    reviews: generateReviews('Meera Chauhan', 4.7),
  },
  {
    id: '40',
    name: 'Arif Ahmed',
    serviceTypes: ['Other', 'Handyman'],
    rating: 4.4,
    location: 'Srinagar, Jammu & Kashmir',
    profileImageUrl: 'https://placehold.co/400x300.png?text=Arif+A',
    bio: 'Specialized in traditional Kashmiri wood carving (Other) and general handyman tasks in Srinagar. Bringing artistry and utility to your home.',
    experienceYears: 20,
    hourlyRate: 'Contact for quote', // Specialized skill
    reviewsCount: 65,
    portfolioImages: [
      'https://placehold.co/600x400.png?text=Wood+Carving+Detail',
      'https://placehold.co/600x400.png?text=Custom+Furniture',
    ],
    reviews: generateReviews('Arif Ahmed', 4.4),
  }
];

